import "./globals.css";

export const metadata = {
  title: "Empresa",
  description: "Generated by create next app",
  icons: {
    icon: '/logo-construccion.png',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
      >
        {children}
      </body>
    </html>
  );
}
